name: interactive_modal
description: A Flutter package for displaying interactive modals over background content while maintaining full interactivity with both. Features draggable modals, customizable positioning, smooth animations, backdrop overlay, and event callbacks.
version: 0.1.0
homepage: https://github.com/kevindels/flutter_interactive_modal
repository: https://github.com/kevindels/flutter_interactive_modal
issue_tracker: https://github.com/kevindels/flutter_interactive_modal/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
